apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yml
  - gateway.yml
  # media apps
  - plex/
  - qbittorrent/
  - jackett/
  - sonarr/
  - radarr/
  - calibre/
  - soulseek/
