apiVersion: v1
kind: ConfigMap
metadata:
  namespace: unifi
  name: unifi-controller-mongo-init-script
data:
  init-mongo.js: |
    db.getSiblingDB("unifi").createUser({
      user: "unifi",
      pwd: "${MONGO_PASS}",
      roles: [
        { role: "dbOwner", db: "unifi" },
        { role: "dbOwner", db: "unifi_stat" }
      ]
    });
