apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unifi
resources:
  - namespace.yml
  - secret.yml
  - configmap.yml
  - deployment.yml
  - service.yml
  - pvc.yml
  - gateway.yml
