apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quixit
resources:
  - namespace.yml
  - secret.yml
  - deployment.yml
  - service.yml
  - pvc.yml
  - gateway.yml
  - automation/
