apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ninjam
resources:
  # - ninjam.ns.yml
  # - ninjam.configmap.yml
  # - ninjam.pvc.yml
  # - ninjam.deployment.yml
  # - ninjam.service.yml
  # - ninjam.cronjob.yml
