apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-scripts
  namespace: filebrowser
  labels:
    app: filebrowser
data:
  init-filebrowser.sh: |
    #!/usr/bin/env sh
    /bin/filebrowser config init --database /database/filebrowser.db
    /bin/filebrowser config set \
        --database /database/filebrowser.db \
        --port 44301 \
        --address 0.0.0.0 \
        --baseurl "/" \
        --root "/srv" \
        --branding.name "hi, welcome." \
        --branding.disableExternal
    /bin/filebrowser users add ${FILEBROWSER_USER} ${FILEBROWSER_PW} --perm.admin --database /database/filebrowser.db
    exec /bin/filebrowser --port 44301 --disable-exec --database /database/filebrowser.db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: filebrowser
  labels:
    app: filebrowser
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:v2.59.0
          imagePullPolicy: IfNotPresent
          env:
            - name: FILEBROWSER_USER
              valueFrom:
                secretKeyRef:
                  name: filebrowser-credentials
                  key: FILEBROWSER_USER
            - name: FILEBROWSER_PW
              valueFrom:
                secretKeyRef:
                  name: filebrowser-credentials
                  key: FILEBROWSER_PW
          volumeMounts:
            - name: filebrowser
              mountPath: /srv
              subPath: files
            - name: filebrowser
              mountPath: /database
              subPath: database
            - name: filebrowser-scripts
              mountPath: /scripts
          ports:
            - containerPort: 44301
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              memory: 512Mi
          command: ["/bin/sh", "-c", "/scripts/init-filebrowser.sh"]
      volumes:
        - name: filebrowser
          persistentVolumeClaim:
            claimName: filebrowser
        - name: filebrowser-scripts
          configMap:
            name: filebrowser-scripts
            defaultMode: 0755
