apiVersion: ENC[AES256_GCM,data:ePQ=,iv:madxdtP3C075btogQLkaiPWuQNR5UAz53qFL6xMbHSk=,tag:/18/okshkUa0u3DCL1CDKQ==,type:str]
kind: ENC[AES256_GCM,data:xTo97pjP,iv:LFRfotghtGHJkWMmxHbl8kCW2POginf4bkwXHjzWte8=,tag:ehpdwpyM5FLaMQuEHtRkYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dNPHtLMYSm0pWyUEEe+Q,iv:O/FQiEnxStk73LRjEQL5A41z3vBV4O4l2tua0c2T3C0=,tag:AK60fF1zNktDqnNJgdbI/w==,type:str]
    namespace: ENC[AES256_GCM,data:g7dACzGCh4X8arM=,iv:UmNzBi/Tkcg5seWuwDdvl+af0vl2FPuHiByZtzulN4E=,tag:h7l68ZbFm3HGoYhf/lfpug==,type:str]
type: ENC[AES256_GCM,data:ISRa3uOW,iv:QizzPtIy5HvCEoHbULs2pDDjZhxGe9fSiVY3cYEd1v0=,tag:WaHzRbNgo0jmMvGy28MNSg==,type:str]
stringData:
    #ENC[AES256_GCM,data:3ZJMybbHMtMalMrCdpmV2q4CncOMZ8pX,iv:aA90b6DKFoGVIDYUsAmfpzc9AZlbEuDzjfjhBgYPJkk=,tag:NjcitCo4Dvk6T/twAeqp+w==,type:comment]
    NINJAM_USER: ENC[AES256_GCM,data:FTyT5kY=,iv:cvMVMdUoOl8gRzS/zZNRYPEBgHA5FAECh+J0PeHnuMw=,tag:6Vu69h+zn4r4LcP0djorOA==,type:str]
    NINJAM_PASSWORD: ENC[AES256_GCM,data:jZZnE+VZ,iv:2gbuR2G79k9EEHJ/m2KJaXOl+xZRZLzw1ISSnt667uU=,tag:T1jFYDBnMsfkqsst5+NeUw==,type:str]
    FILEBROWSER_USER: ENC[AES256_GCM,data:fbY88WAb/dOj1Q==,iv:W6Yi/DeOKIAdyDS4RlhZFf1zJn7yjvNe9aSUgld5pdc=,tag:PSjzJ09mok7bObhbWtKYag==,type:str]
    FILEBROWSER_PW: ENC[AES256_GCM,data:jlPbvZiFcNfyXz4ICVc=,iv:Z0xN6iZGYIHo+KM9J9nNBYRJWIiF5MwhLwMlT/8EBWU=,tag:w7NQcL4Uc/X3JnF9lTm9kA==,type:str]
    QUIXIT_USER: ENC[AES256_GCM,data:gj1/47luWSBTVdH/No0yhA==,iv:GKYcm6gxsuUqOS0VSuiHtcqXhcKXaKzn6/uiS1clHtU=,tag:vhmHB+P1Z47OSq/jtDbtGQ==,type:str]
    QUIXIT_PW: ENC[AES256_GCM,data:GAeHobjzXZWRZ78OsXCHfKnNMCE=,iv:Z6I3/cOo/nrL0tC4rRmtseVlbt2iU8j+0yOcTUgE1vc=,tag:HNPL/wCnr8ovPwTONvPrYQ==,type:str]
    SOJU_PW: ENC[AES256_GCM,data:OPuDDTHcjENpQMC2w+M=,iv:JKb/XP5xaLp0mSpA8sfSDQriq4NrmEzZnneLRrLpCpg=,tag:BxF1eVzZ9pmJRn1+iiGbGg==,type:str]
    LIBERA_PW: ENC[AES256_GCM,data:8bWOAPV1zXZonrPdakA=,iv:ZC3ORWuITIC9LirFZ78hzbWLmesyTPF5JMWz25tzf/c=,tag:vPfttECWz6f0PSJeH3f+cw==,type:str]
    CALIBRE_USER: ENC[AES256_GCM,data:UHboHKOG649rhQ==,iv:jzKTkUjmq5vceiX/xXZyi9cJTyEe2g3SCR69CfQp+uw=,tag:kx9Qwuqhfp//YVNxlptE2A==,type:str]
    CALIBRE_PASSWORD: ENC[AES256_GCM,data:12shHnsMl20qK8wZ70w=,iv:OuhymFLV/ByiRx996+cz7G0iOq0k+HeZ2P25+Jejaf0=,tag:d6OKnODD6ehTYn++9b33dg==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:xn+d1SS+dsuOVXuGSPqE2s3rGAMS/HGDomc=,iv:C0IqZeLBaPkjGmDxgGBuMO+pZX3JsHVLGUm1+tVKGmk=,tag:nIu0QYcPEs49p+2IFbzrtg==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:tKBOri27rn5szP44duoWlGD9DFE=,iv:oKzUIG6lHwB2gou/gdEz2KkvFiIK2JEAPKryLFDFYkI=,tag:mf0MdCh4dEvm+t382D8KlA==,type:str]
    #ENC[AES256_GCM,data:6h+fHmFZHlGC1H4rq63fV0iyPM8s+paCGfSKpVy06QuKvA==,iv:1K68Ae545ZIOd8y5WoON1/6inCv+xK7FNFz+WIUpctg=,tag:IZyhGj9XxHSyUmqW8a7lqg==,type:comment]
    SOULSEEK_VPN_KEY: ENC[AES256_GCM,data:wPC7s355OaLdrqhg0xK+kbJgiMJGjeBnOVJKfXocdxgUGcHdu7lLNBnTYNM=,iv:yxVptVmF14Gw70UpPeQ27JtalH8uuFam8itz0XdTnb0=,tag:fg+m1g+Z5DhjEgW99V9oNQ==,type:str]
    QBT_VPN_KEY: ENC[AES256_GCM,data:0EaHnsk80rsKT7eTMkAgVASO9qvlqdnRcWZaOGcrpESEuFyc9EdRhMTX93I=,iv:W1molGXfin7O364D3a7XRu5+11xHC4rGr+HRKWMlsck=,tag:AXUQD5XiaajKDzoCsOlwkA==,type:str]
    JACKETT_VPN_KEY: ENC[AES256_GCM,data:O6PuVDtWcZ0JUCm4x7kFZhNJZ6smzq74sYVAhWIXE4Vij8EkH2RQsAL0rRE=,iv:fLvtKHfcnaQPLzSudNzQS4hAv43CNW6bdry5B9BfMro=,tag:zS4woIMjJ8NQUkJQ7X606g==,type:str]
    #ENC[AES256_GCM,data:tOhMJ8B38JyFwfZcm9YptQ==,iv:8HpaSxENjJWsHiEeo2cgpitpkunR4gmmO+YEhT9AK3c=,tag:RspVt6sSlzxHuAkXPkKgdA==,type:comment]
    TS_CLIENT_ID: ENC[AES256_GCM,data:/EUCE0ezsMQdXS87,iv:hcx0hA2SQ/YSJ9MYT25FfwjXYXlJQylp8aR+nH4pAjs=,tag:D7fk8rOn2vBCF7b0LdUkjg==,type:str]
    TS_CLIENT_SECRET: ENC[AES256_GCM,data:pP4G7yKegROlqpbD0gXOlkeMeLTNRN/8/XSdo/DHn6BI1TnQ1kzs24g4XgS9kR+Yq9nibU2qKOwrXw==,iv:KDh+rihyQh5O+mFxceZdQHooZ+AJnAFA7LItWbJ0J7I=,tag:lNHlA0+r17h0KpvQ9qt3pw==,type:str]
sops:
    age:
        - recipient: age15tc0zhh8daq8xk4ydnzhzjfp8nh3sve93a65r5wfypk38lzgdqkqp5l4wv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V29mcllzR2pwTFdEVk5O
            VGpUMzA1MVRWYWtHbFE1eExyOCtNajFNNXo0Ck9IZTMydklwTkV3enhwL1hqSWdS
            cnhjZ3U2Z210aUhlcTIzTUFscEdFMjgKLS0tIFNaL2Q2WVNtMFNJaFZzN2EreGVx
            WjBBeDZrMzN2L1dNYVVjR0JzVFl0K2sKDnfauAygqmkyfBSNlbI5Ad6CbHPdyUq8
            XlHyxYQvI3j5MnvPWuylbUJa3/Fd74JyXd8x+3pSqsU6z+SPMrSi2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T05:46:25Z"
    mac: ENC[AES256_GCM,data:AYBTvAcy21tWVgQs8AQrPRMV+vzldvzJYLKGOj+x1cV0HYX1YkOMrLiS1GtwUqISbsVWPp6fOWSSNAINI15/VINuHPAHSigF/jwmLQxW+Y74bPdttG2J8SwXMFPjVETJIIvajzEH2T6hMubw2i4X76+07Q/t2JhhHdBjU8HaYzk=,iv:Z9yHnD+VNxLgal3aw5EkuhiCIX4g6qU0sY1NfvwTfr0=,tag:RXtGmBwdJdQdZ1IeToR+0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
