apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ha
resources:
  # - ha.ns.yml
  # - generic-device-plugin.yaml
  # - ha.pvc.yml
  # - ha.deployment.yml
  # - ha.service.yml
  # - zwave.deployment.yml
  # - zwave.service.yml
