apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: soulseek
 name: soulseek
 namespace: media
spec:
 replicas: 1
 strategy:
  type: Recreate
 revisionHistoryLimit: 3
 selector:
  matchLabels:
   app: soulseek
 template:
  metadata:
   labels:
    app: soulseek
  spec:
   hostname: soulseek
   initContainers:
    - name: sysctl-setup
      image: busybox
      command:
       [
        'sh',
        '-c',
        'sysctl -w net.ipv4.conf.all.rp_filter=2 && sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv4.ip_forward=1',
       ]
      securityContext:
       privileged: true
   containers:
    - name: gluetun
      image: qmcgaw/gluetun:v3.40.3
      securityContext:
       capabilities:
        add:
         - NET_ADMIN
       privileged: true
      env:
       - name: VPN_SERVICE_PROVIDER
         value: protonvpn
       - name: VPN_TYPE
         value: wireguard
       - name: WIREGUARD_PRIVATE_KEY
         valueFrom:
          secretKeyRef:
           name: soulseek
           key: key
       - name: WIREGUARD_ENDPOINT_IP
         value: '185.90.60.210'
       - name: SERVER_COUNTRIES
         value: 'Finland'
       - name: VPN_PORT_FORWARDING
         value: 'on'
       - name: FIREWALL
         value: 'yes'
       - name: HEALTHCHECK_TARGET
         value: 'ip.me:443'
      volumeMounts:
       - mountPath: /dev/net/tun
         name: tun-device
      resources:
       requests:
        cpu: 100m
        memory: 512Mi
       limits:
        memory: 512Mi
    - name: soulseek
      image: realies/soulseek:latest
      imagePullPolicy: Always
      env:
       - name: PGID
         value: '1000'
       - name: PUID
         value: '1000'
      ports:
       - containerPort: 6080
         name: web-soulseek
      resources:
       requests:
        cpu: 1
        memory: 1800Mi
       limits:
        memory: 1800Mi
      volumeMounts:
       - name: media-config
         mountPath: /data/.SoulseekQt
         subPath: soulseek/data
       - name: media-config
         mountPath: /data/Soulseek Chat Logs
         subPath: soulseek/chat_logs
       - name: media-data
         mountPath: /data/Soulseek Downloads
         subPath: downloads/soulseek
       - name: music-data
         mountPath: /data/Soulseek Shared Folder/music
   dnsPolicy: None
   dnsConfig:
    nameservers: ['1.1.1.1', '1.0.0.1']
   volumes:
    - name: media-config
      persistentVolumeClaim:
       claimName: media-config
    - name: media-data
      persistentVolumeClaim:
       claimName: media-data
    - name: music-data
      persistentVolumeClaim:
       claimName: music-data
    - name: tun-device
      hostPath:
       path: /dev/net/tun
       type: CharDevice
   nodeSelector:
    kubernetes.io/arch: amd64
