apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quixit
resources:
  - quixit.cronjob.yml
  - quixit.job.create.yml
  - quixit.job.finalize.yml
  - quixit.job.transition-to-songs.yml
